name: Sync to GitHub

on:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Sync Changes
      run: |
        cd ${{ github.workspace }}
        git add .
        git commit -m "Sync at $(date)"
        git push
