name: Sync to GitHub

on:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch Changes
      run: git fetch

    - name: Debug Information
      run: |
        git status
        git branch -vv

    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Sync Changes
      run: |
        git pull origin main  # Pull changes from the remote branch
        git add -A  # Stage all changes, including untracked files
        git status  # Print the status for debugging purposes
        git commit -m "Sync at $(date)"
        git push
